### ISSUE TITLE
Outdated device lists in RzChromaSDKDefines.h

### ISSUE THREAD

**Issue by gooday2die** [razerofficial/CSDK_SampleApp#3]
`RzChromaSDKDefines.h` has outdated device lists. 
I was working on my projects and someone including me had an issue that we have missing devices in `RzChromaSDKDefines.h`.

I was waiting for Razerofficial to release a new version `RzChromaSDKDefines.h` for a long time but they did not till now.
(As you can see [here](https://github.com/razerofficial/CSDK_SampleApp/blob/master/Razer/RzChromaSDKDefines.h) that it was generated 4 years ago)

So I am reporting this issue to this repo.

For example, I personally own 
- DeathAdder Elite Chroma
- Deathadder V2

Both devices work fine with setting RGB with `SetEffect`. 
However Deathadder V2 is not able to `QueryDevice` since no GUID is provided in `RzChromaSDKDefines.h`.

One of alternative ways of retrieving connected Razer devices would be using win32 api however that is kind of lot slower and inaccruate than using pure RazerSDK. 

So it will be nice if `RzChromaSDKDefines.h` gets latest devices updated in them.
Thanks

**Comment by tgraupmann** [comment]
The latest GUIDs can be found here.
https://assets.razerzone.com/dev_portal/C%2B%2B/html/en/_rz_chroma_s_d_k_defines_8h_source.html

The sample apps aren't using the GUIDs but I'll make sure to update the list.

**Comment by gooday2die** [comment]
@tgraupmann Thanks for your reply. 

> https://assets.razerzone.com/dev_portal/C%2B%2B/html/en/_rz_chroma_s_d_k_defines_8h_source.html 

I already was using the latest  RzChromaSDKDefines.h, however it had outdated GUIDs. 
*Ex) `Deathadder V2` does not exist on the latest RzChromaSDKDefines.h as well.*

The reason that I made an issue on this repository about this outdated GUID was that I had no other options of contacting Razer official on the topic and this repository was the most active repository that Razer official had. I just wanted to give Razer a heads up about outdated GUID list so that they might be able to update the list, rather than keeping it outdated for more time. 

I would like to apologize if this issue was a bit off for this repository. However this was my only way of making contact to Razer. 

Also thanks for the reply.

**Comment by tgraupmann** [comment]
Hi @gooday2die feedback is always welcome! I'll talk to the engineer and get the docs and source updated. Thanks for the heads up!

**Comment by gooday2die** [comment]
@tgraupmann Thank you so much for your help 👍

**Comment by tgraupmann** [comment]
Hi @gooday2die 

```
Razer DeathAdder V2 will use Razer DeathAdder's device GUID since they're the same family.
```

**Comment by gooday2die** [comment]
@tgraupmann Thanks for your reply. 

> Razer DeathAdder V2 will use Razer DeathAdder's device GUID since they're the same family.

If those two devices share the same GUID, that will mean
- If I plug in Razer DeathAdder V2
- Then `QueryDevice` with `ChromaSDK::DEATHADDER_CHROMA` or `ChromaSDK::DEATHADDER_ELITE_CHROMA`
- One of those two devices *should* say that it is connected.

However, when I plug in my DeathAdder V2 and run following code
```cpp
#include <iostream>
#include <string>
#include <tchar.h>
#include <windows.h>

#include "./includes/RzChromaSDKDefines.h"
#include "./includes/RzChromaSDKTypes.h"

#define CHROMASDKDLL        _T("RzChromaSDK64.dll")

int main() {
    typedef RZRESULT(*INIT)();
    typedef RZRESULT(*UNINIT)();
    typedef RZRESULT(*QUERYDEVICE)(RZDEVICEID DeviceId, ChromaSDK::DEVICE_INFO_TYPE& DeviceInfo);

    HMODULE m_ChromaSDKModule = LoadLibrary(CHROMASDKDLL); // Load dll
    QUERYDEVICE QueryDevice = reinterpret_cast<QUERYDEVICE>(GetProcAddress(m_ChromaSDKModule, "QueryDevice"));
    INIT Init = (INIT)GetProcAddress(m_ChromaSDKModule, "Init");
    UNINIT UnInit = (INIT)GetProcAddress(m_ChromaSDKModule, "UnInit");

    if (!Init()) {
        std::cout << "Init Success!" << std::endl;

        ChromaSDK::DEVICE_INFO_TYPE deviceInfo1 = {};
        ChromaSDK::DEVICE_INFO_TYPE deviceInfo2 = {};

        QueryDevice(ChromaSDK::DEATHADDER_CHROMA, deviceInfo1); // Query device with Deathadder chroma
        QueryDevice(ChromaSDK::DEATHADDER_ELITE_CHROMA, deviceInfo2);  // Query device with Deathadder Elite Chroma

        std::cout << "DEATHADDER_CHROMA connected : " << std::to_string(deviceInfo1.Connected) << std::endl;
        std::cout << "DEATHADDER_ELITE_CHROMA connected : " << std::to_string(deviceInfo2.Connected) << std::endl;

        UnInit();
    } else {
        std::cout << "Init failed" << std::endl;
    }
    return 0;
}
```

This results following output
```
Init Success!
DEATHADDER_CHROMA connected : 0
DEATHADDER_ELITE_CHROMA connected : 0
```
Meaning that DeathAdder V2 is not recognized as either one of  `ChromaSDK::DEATHADDER_CHROMA` or `ChromaSDK::DEATHADDER_ELITE_CHROMA`.

However the main intention of this issue was that `RzChromaSDKDefines` could get an update for GUID so that devlopers like me will not see their connected devices not appear as connected.  

I am sorry for bugging you so much.
Thanks again for your help and for your time as well.

**Comment by tgraupmann** [comment]
Unfortunately, it's possible this is actually a bug. The `QueryDevice` method is scheduled to be deprecated. The method won't be removed from the library, but it is scheduled to be removed from the documentation.

**Comment by gooday2die** [comment]
@tgraupmann Thanks too bad ... Thanks for your help! I will look for other ways to figure it out! You helped me a lot.
